### ISSUE TITLE
named formlets & lists

### ISSUE THREAD

**Issue by goolord** [goolord/ditto#5]
currently, a desirable use of ditto is to take an `f a` and a `Form a` and produce a `Form (f a)`. this is sort of already possible except that the parsing function will get mangled. if you try passing something that will parse `f a`, you no longer have a `Form a`, and it won't compose well.

**Comment by goolord** [comment]
well, you can *kindof* do this now. i should probably add some helper functions at some point, but the error handling functions allow you to hack this, which is close enough for now

**Comment by chessai** [comment]
what kind of structure does f take here?
